snippet_path : "/nfsdataLite/US_Census_Data/3_Snippets/1950/Group_5_other/"
finished_path : "/nfsdataLite/US_Census_Data/3_Snippets/Finished/1950/Group_5/"
output_path : "/nfsdataLite/US_Census_Data/4_HWR_Out"
year : 1950
archive: False
run_batches: True
delete_snippets : False
move_snippets : False
batch_size: 100000
images_count: 10100000
column_model_list:
  - Name:
      - "T1940_A1950_Name_Prod"
      - "LastDetector_Prod"
  - Age:
      - "T1940_A1950_Age_Prod"
      - "T1950_A1950_BirthMonth_Prod"
  - Relationship_To_Head:
      - "T1940_A1950_Relation_Prod"

